products = [
  {
    '_id': "1",
    'name': "Alter Ego",
    'image': "/images/alterego.jpg",
    'description':
      "A house of patterns. Somewhere it's zig-zag, somewhere its curves, or its a circle, it's triangular, there are waves and abstract lines. There are colors, there are shapes. And it's all over, overlapping on each other. This is how the Alter Ego’. Classic Wallet Tyvek® paper wallet was designed. For the art fanatics, the in-house product is a combination of all the lines and marks that makes the world look real. The alternate of fake perfection.",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 999.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': "2",
    'name': "Carbon Wave",
    'image': "/images/carbonwave.jpg",
    'description':
      "The dark tides are getting very high! The Carbon Wave Classic Wallet Tyvek® paper wallet will show you the alternate realm of carbon. The sharp black and grey waves are giving the wallet a really hand-stitched touch. For people who believe in simplicity, this wallet is a perfect match. When carbon footprint scales breaking the graph, we bring a wallet of such design.",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 799.99,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': "3",
    'name': "More to life",
    'image': "/images/moretolife.jpg",
    'description':
      "Part of our Artist Collaboration program, the More to Life Superwallet is artwork by Dave Faint. This design is An examination of the concept of what ‘life’ actually is. Juxtaposing the idea of existence on an abstract level. Everything is stardust, yet life has its own path. Everything is constantly growing and dying.",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 699.00,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': "4",
    'name': "Royal Blaze",
    'image': "/images/royalblaze.jpg",
    'description':
      "Made for the nomads, the travelers, the BIKERS. The Royal blaze Classic Superwallet is a must have!",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 799.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': "5",
    'name': "Skatelife",
    'image': "/images/shatelife.jpg",
    'description':
      "Push, flip, pop shovel & skate! This artwork featuring a unique skate edition, is part of Supervek Artist collaboration. The art by Colombian Street artist Gavilan is bound to be the envy of the skate park and streets alike. Watcha waiting for? Just Send it!",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 799.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': "6",
    'name': "Super Shark",
    'image': "/images/supershark.jpg",
    'description':
      "This iconic design is a tribute to the legendary Flying Tigers from World War 2. From December 1941 to July 1942, a retired U.S army officer and a group of volunteers were the only effective defence in East Asia against Hitlers allies - the Japanese. The legendary volunteer group was known as the Flying Tigers. In the fall of 1941, their squadrons adopted the soon to be famous paint scheme - the menacing Shark.",
    'brand': "SuperWallet",
    'category': "Wallet",
    'price': 999.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]

