# Generated by Django 3.1.7 on 2021-03-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='state',
        ),
    ]
